// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import SectionTabsController from "./section_tabs_controller"
application.register("section-tabs", SectionTabsController)
